[package]
name = "autoresolve-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
streaming-iterator = "0.1.9"
tree-sitter = "0.27.0"
tree-sitter-python = "0.25.0"
